### ISSUE TITLE
feat: Support more complex type whens defaulting TF vars

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix-cli#115]
The merging of #113 added support for basic defaults, e.g.:

```
variable "timeout_seconds" {
  type        = number
  description = "Timeout for each request"
  default     = 120
}
```

Produces API field:
```
                timeout_seconds:
                  default: "120"
                  description: Timeout for each request
                  type: number
```

However it did not support more complex defaults, such as variables with:
```
variable "ports" {
  type = object({
    name = string
    port = number
  })
  description = "Port which the container listens to (http1 or h2c)"
  default = {
    name = "http1"
    port = 8080
  }
}
```

The default being an object presented more complexity and requires further exploration and testing of edge cases before it can be supported.
