### ISSUE TITLE
bug: helm instance configure image has runner incompatible issue on eks

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/kratix-cli#49]
With a promise definition:
```
...
  workflows:
    promise:
      configure:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
          spec:
            containers:
            - env:
              - name: CHART_URL
                value: oci://registry-1.docker.io/bitnamicharts/mysql
              image: ghcr.io/syntasso/kratix-cli/helm-resource-configure:v0.1.0
              name: instance-configure
```

resource configure helm instance configure pipeline fails with
```
k logs kratix-mysql-example-mysql-instance-configure-7c4f8-xwrzh -c instance-configure
exec /bin/sh: exec format error
```

No issue running kind.
