### ISSUE TITLE
[bug] kratix-cli crash if crossplane XRD has empty spec in the defined schema

### ISSUE THREAD

**Issue by johnfawzy84** [syntasso/kratix-cli#86]
## What happened ? 
tried to create a crossplane based promise, with an XRD that contain an empty spec. like the following : 
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpstorages.domain.com
spec:
  group: domain.com
  names:
    kind: XpStorage
    singular: xpstorage
    plural: xpstorages
  claimNames:
    kind: HyperScalerStorage
    singular: hyperscalerstorage
    plural: hyperscalerstorages
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
```
the command was like this : 
```sh
kratix init crossplane-promise xpstoragepromise -c ../XpStorage/compositions/compositions.storage.yaml -x ../XpStorage/xpstorage.xrd.yaml -g domain.com -k XpStoragePromise 
```
## Observation/reaction 
The following error message/stack trace returned 
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/syntasso/kratix-cli/cmd.generateCRDFromXRD(0xc0004daf00)
        /home/devdock/go/pkg/mod/github.com/syntasso/kratix-cli@v0.5.0/cmd/init_crossplane_promise.go:197 +0x405
github.com/syntasso/kratix-cli/cmd.InitCrossplanePromise(0xc00060e400?, {0xc000796cf0?, 0x4?, 0x3eab4f5?})
        /home/devdock/go/pkg/mod/github.com/syntasso/kratix-cli@v0.5.0/cmd/init_crossplane_promise.go:92 +0x2bb
github.com/spf13/cobra.(*Command).execute(0x5cf3f20, {0xc000796c60, 0x9, 0x9})
        /home/devdock/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0x5cf4d80)
        /home/devdock/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/devdock/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/syntasso/kratix-cli/cmd.Execute({0x3eac331?, 0xc000002380?})
        /home/devdock/go/pkg/mod/github.com/syntasso/kratix-cli@v0.5.0/cmd/root.go:31 +0x50
main.main()
        /home/devdock/go/pkg/mod/github.com/syntasso/kratix-cli@v0.5.0/cmd/kratix/main.go:27 +0x25
```
## expectation 
that kratix-cli will generate a promise normally, probably with `api`section looks like that : 
```yaml
api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      creationTimestamp: null
      name: xpstoragepromises.bode.dev.bosch.com
    spec:
      group: bode.dev.bosch.com
      names:
        kind: XpStoragePromise
        plural: xpstoragepromises
        singular: xpstoragepromise
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  compositeDeletePolicy:
                    default: Background
                    enum:
                    - Background
                    - Foreground
                    type: string
                  compositionRef:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  compositionRevisionRef:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  compositionRevisionSelector:
                    properties:
                      matchLabels:
                        additionalProperties:
                          type: string
                        type: object
                    required:
                    - matchLabels
                    type: object
                  compositionSelector:
                    properties:
                      matchLabels:
                        additionalProperties:
                          type: string
                        type: object
                    required:
                    - matchLabels
                    type: object
                  compositionUpdatePolicy:
                    enum:
                    - Automatic
                    - Manual
                    type: string
                  publishConnectionDetailsTo:
                    properties:
                      configRef:
                        default:
                          name: default
                        properties:
                          name:
                            type: string
                        type: object
                      metadata:
                        properties:
                          annotations:
                            additionalProperties:
                              type: string
                            type: object
                          labels:
                            additionalProperties:
                              type: string
                            type: object
                          type:
                            type: string
                        type: object
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  resourceRef:
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      name:
                        type: string
                    required:
                    - apiVersion
                    - kind
                    - name
                    type: object
                  writeConnectionSecretToRef:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                type: object
            type: object
        served: true
        storage: true
    status:
      acceptedNames:
        kind: ""
        plural: ""
      conditions: null
      storedVersions: null
  
```

Hint : adding just one element can be a workaround.
